language: python


python:
  - "2.7"
# command to run tests
script: python error1/error_use1.py
script: python error2/error_use2.py
script: python recommended/main1.py
script: python recommended/main2.py

